export const businessCategories = [
  "restaurant",
  "cafe",
  "bakery",
  "catering",
  "barbershop",
  "nail_salon",
  "beauty_salon",
  "gym",
  "studio",
  "photographer",
  "wedding_venue",
  "event_planner",
  "florist",
  "hotel",
  "dacha",
  "digital_marketing_agency",
  "real_estate",
  "travel_agency",
  "auto_service",
  "clinic",
  "tutoring",
  "tailor",
  "cleaning_service",
  "other",
] as const;

export type BusinessCategory = (typeof businessCategories)[number];
